require("config.globals")
require("config.options")
require("config.filetypes")

require("plugins.plenary")
require("plugins.snacks")
require("plugins.gruvbox")
require("plugins.treesitter")
require("plugins.mini")
require("plugins.telescope")
require("plugins.oil")
require("plugins.fidget")
require("plugins.showkeys")
require("plugins.harpoon")
require("plugins.atone")
require("plugins.gitsigns")
require("plugins.lsp")
require("plugins.conform")
require("plugins.lualine")
require("plugins.which-key")
require("plugins.tmux-navigator")
require("plugins.trouble")
require("plugins.claude")
require("plugins.copilot")

require("config.keymaps")
require("config.autocmds")
require("config.colorscheme")
